### ISSUE TITLE
Override Option

### ISSUE THREAD

**Issue by dmahtani** [wemake-services/caddy-gen#10]
Hello. It would be useful to have an override option. For example, if you deploy Rocket.Chat behind an Reverse Proxy SSL then the Caddy file needs to look like this:

```
your_domain.com {
        proxy / 127.0.0.1:3000 {
                proxy_header X-Forwarded-Proto {scheme}
                proxy_header X-Forwarded-For {host}
                proxy_header Host {host}
                websocket
        }
}
```
If there was a way to override the entire entry to make applications that require more complicated Caddy file entries so that it can work behind the reverse proxy that would be useful.

**Comment by ro31337** [comment]
What api do you expect, do you have any idea?

**Comment by dmahtani** [comment]
Perhaps there could be a virtual.params label where we could insert a comma-separated list of subdirectives for the proxy directive, such as transparent or websocket.

Similar to this:

https://github.com/Whitestrake/caddy-gen

**Comment by sobolevn** [comment]
@dmahtani this looks very complicated.

Maybe we can use `import` instead? https://caddyserver.com/docs/import

**Comment by dmahtani** [comment]
Would it be difficult to add one more env label called **virtual.params**? Most of the time we just need to add the _transparent_ and/or _websocket_ directives.

**Comment by sobolevn** [comment]
@dmahtani could you please send a PR with the implementation?

**Comment by AkgunFatih** [comment]
05/2020 and still nothing
what a bullshit waste of time

Thank you

**Comment by sobolevn** [comment]
> 05/2020 and still nothing

Go and implement it yourself, no one has a signed contract with the deadline on their hands.

> what a bullshit waste of time

One more comment like this and I will block you. Please, respect other people.
