### ISSUE TITLE
Add `tls-email` alias `tls` or `tls-config`

### ISSUE THREAD

**Issue by HugoDF** [wemake-services/caddy-gen#18]
`virtual.tls-email` actually gets injected as the value for the `tls` directive, which means you can pass a TLS key pair as well as an email.

eg. I pass the path to the certificate/key pair here: https://github.com/HugoDF/docker-compose-local-https/blob/master/caddy-gen/docker-compose.yml#L18

Having a `tls` or `tls-config` value would be nice from a semantics point of view (it feels a bit odd to do `"virtual.tls-email=/root/certs/foo.test.pem /root/certs/foo.test-key.pem"`)

Seeing as I've figured the above out from reading the template I would be happy to contribute such an alias if it's likely to be accepted.

**Comment by sobolevn** [comment]
Ok, let's do it.
