### ISSUE TITLE
registration error: acme: Error 403

### ISSUE THREAD

**Issue by masterkain** [wemake-services/caddy-gen#25]
```
caddy-gen       | caddy.1    | 2019/12/05 04:31:38 registration error: acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled.
Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

**Comment by masterkain** [comment]
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/7

**Comment by masterkain** [comment]
https://caddyserver.com/v1/blog/caddy-0_10_12-released

**Comment by sobolevn** [comment]
Oh, thanks! @masterkain can you please change the Caddy version here: https://github.com/wemake-services/caddy-gen/blob/master/Dockerfile#L7

And then I will make a new release.

**Comment by ffminus** [comment]
New Caddy versions need explicit agreement for the Let's Encrypt license.
Adding `--agree true` to the Caddy options in `Procfile` does the trick.

**Comment by sobolevn** [comment]
Awesome! @ffminus can you please send a PR?

**Comment by ffminus** [comment]
Done. Could approve it and create the new tag so we can pull it from Docker Hub?

**Comment by sobolevn** [comment]
Sure, `0.2` is on its way.
