### ISSUE TITLE
https redirect

### ISSUE THREAD

**Issue by neoromantique** [wemake-services/caddy-gen#32]
I would like to add a way to redirect http requests to https uri without utilising a different container, is it possible to add an option for this?

**Comment by sobolevn** [comment]
@neoromantique sure! Isn't it on by default?

**Comment by neoromantique** [comment]
> @neoromantique sure! Isn't it on by default? PRs are more than welcome!

I've done it now by simply providing my own caddy template file as volume, would you want a  PR with env var for this functionality?

**Comment by sobolevn** [comment]
@neoromantique sure! Thanks!

**Comment by neoromantique** [comment]
This is no longer relevant as this is now default behavior in caddy.
