### ISSUE TITLE
Certificate written to disk -> No duch file or directory

### ISSUE THREAD

**Issue by AlphaMoonbaseBerlin** [wemake-services/caddy-gen#34]
Hi. I#m pretty new to the whole backend spiel so mayb this is not an issue at all and just a simple error.

When activating TSL via
` - "virtual.tls-email=admin@mydomain.com"  # ssl is now on`
I get the following error:

```
caddy.1    | Activating privacy features...                                                      
2020/05/02 15:49:26 [INFO][www.sub.mydomain.com] acme: Obtaining bundled SAN certificate
caddy.1    | 2020/05/02 15:49:27 [INFO][] Certificate written to disk: /etc/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
caddy.1    | 2020/05/02 15:49:27 open /etc/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.sub.mydomain.com/www.sub.mydomain.com.crt: no such file or directory
forego     | starting caddy.1 on port 5200
forego     | sending SIGTERM to caddy.1
forego     | sending SIGTERM to dockergen.1
dockergen.1 | 2020/05/02 15:49:27 Received signal: terminated
```
From my Understanding the certificate proces is working, but there seemsto be an issue with the recieved certificate not saved under the right name. 

The whole system is working like a charm without TSL, so im hoping that the issue is easy resolvable as this image is really good to setup.

Best

**Comment by sobolevn** [comment]
Can you please post your whole config?

**Comment by AlphaMoonbaseBerlin** [comment]
Hoi. Thanks for the quick response.
Im not 100% sure what happened, but after letting it run overnight with tls disabled and  rebuilding the setup again the next day with tls enabled it suddenly worked.
It got a second error though which was quite easy to fix. Seems like there was a .lock file preventing Caddy from ovewriting it with the new certificate. Starting bash in the conatiner and deleting the .lock file solved the issue. 
I'm not sure if this two issues are releated but maybeit helps someone.

Thanks for the great image, works really great now!

**Comment by sobolevn** [comment]
@AlphaMoonbaseBerlin you are welcome 👍
