### ISSUE TITLE
update to caddy 2.0.0

### ISSUE THREAD

**Issue by AlphaMoonbaseBerlin** [wemake-services/caddy-gen#35]
With caddy being in version 2.0.0 and caddy-gen still sporting version 0.10.12 wouldn't it be a good idea to upgrade to the nwest version?

I tried setting the caddy version in the dockerfile myself, but it wont run. I suppose there is some new stuff about the api in the Caddyfile. 

But maybe there is no real reasson for an update?

**Comment by sobolevn** [comment]
I am not yet familiar with `caddy@2`
I will dig into it soon! Thanks!

**Comment by Siemko** [comment]
I've created similar project, but based on Caddy2: https://github.com/Siemko/caddy2-gen. Feel free to check the differences.

**Comment by sobolevn** [comment]
@Siemko I can add you as a maintainer for this package and merge your changes. Do you want this to happen? 🙂

**Comment by Siemko** [comment]
Yes, sounds interesting :)

**Comment by AlphaMoonbaseBerlin** [comment]
> 
> 
> I've created similar project, but based on Caddy2: https://github.com/Siemko/caddy2-gen. Feel free to check the differences.

Ah, so sweet, thank you alot :) Gonna test it out asap!

**Comment by sobolevn** [comment]
@Siemko awesome! Thanks! PR is more than welcome!
