### ISSUE TITLE
Print IP for debugging purposes

### ISSUE THREAD

**Issue by achembarpu** [wemake-services/caddy-gen#39]
Hey wemake!

Thanks for this project! I was facing a few issues with networking, and it's a bit hard to debug since I can't see the generated Caddyfile from the logs. Would it be possilbe to add an option for this? Or atleast print it next to the domain that is logged currently.

Thanks!

**Comment by Siemko** [comment]
For now, you can see generated Caddyfile, by executing following:
1. `docker ps`
2. Take caddy-gen container ID
3. `docker exec -it <container_id> sh`
4. `cat /etc/caddy/Caddyfile`
