### ISSUE TITLE
Missing Docker version tags

### ISSUE THREAD

**Issue by tonsV2** [wemake-services/caddy-gen#41]
The [latest commit](https://github.com/wemake-services/caddy-gen/commit/5f9437af8af56a558cde76ea3dd052f63b24e29b) includes breaking changes. Which caused a server of mine to become inaccessible. Since there's no image tagged with version 0.3.0 on Docker Hub I can't easily revert.

Also a tag, possible 0.4.0, for the aforementioned commit/release would be nice.

**Comment by sobolevn** [comment]
We had a `0.3.0` release on git: https://github.com/wemake-services/caddy-gen/releases/tag/0.3.0

For some reason `Dockerhub` ignored it.

**Comment by sobolevn** [comment]
@Siemko any ideas how we can fix the CI? https://travis-ci.com/github/wemake-services/caddy-gen/builds/176069791

**Comment by tonsV2** [comment]
> We had a `0.3.0` release on git: https://github.com/wemake-services/caddy-gen/releases/tag/0.3.0
> 
> For some reason `Dockerhub` ignored it.

If the image isn't tagged by the Git commit tag it's probably due to an misconfigured, or not configured at all, build rule.

**Comment by tonsV2** [comment]
Upon further investigation I see that a repository of mine is suffering from the same issue. I've written their support team.

**Comment by tonsV2** [comment]
I've haven't heard anything back from the support team. My suggestion is that a manual tagging is done. I'd do it myself if I had access to the registry.

**Comment by sobolevn** [comment]
The thing is: we don't what to release `1.5.0` while we have our CI broken.
Can you please help fixing it?

**Comment by tonsV2** [comment]
Do you mean release 0.4.0? Either way, I haven't used Travis before but if you point me in the right direction I can take a look

**Comment by sobolevn** [comment]
Yes, `0.4.0` 🙂

**Comment by tonsV2** [comment]
I've created the following pull request #42.

Fixing the curl command was simply done by sleeping for 1 second. However simply doing a curl request is a bit too little. So I wanted to assert the http status code as well. Because port 80 redirects to 443 it returns 308. Following that redirect results in the following.

`curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error`

I'm guessing that is due to lack of configuration but I'm not sure.

**Comment by casperdcl** [comment]
Any chance of pushing a new image to dockerhub?

description | based on | docker image | Caddy version
--|--|--|--
Current | #60 | [wemakeservices/caddy-gen](https://hub.docker.com/r/wemakeservices/caddy-gen) | v2.4.3
My mirror | #90 | [casperdcl/caddy-gen](https://hub.docker.com/r/casperdcl/caddy-gen) | v2.8.4

Later Caddy versions have more features. Took me ages to realise things like 
[`trusted_proxies`](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#trusted_proxies) doesn't work because of the outdated Caddy version.

If you want I can add a GitHub Action CI script to build & push to docker hub :)

**Comment by sobolevn** [comment]
Please! It would be very helpful

**Comment by casperdcl** [comment]
Hopefully you'll push a new tag/release soon @sobolevn :)

**Comment by sobolevn** [comment]
Done: https://github.com/wemake-services/caddy-gen/pkgs/container/caddy-gen/257320540?tag=1.0.0
